// Generated by CoffeeScript 1.6.2
/*
Copyright (c) 2013 Markus Kohlhase <mail@markus-kohlhase.de>
*/


(function() {
  var REQUEST_URL, app, exec, express, fs, runCmd, vlcInstances;

  express = require('express');

  app = express();

  exec = require('child_process').exec;

  fs = require('fs');

  vlcInstances = require('../clients.js');

  REQUEST_URL = '/requests/status.xml?command=';

  app.use('/', express["static"](__dirname + './../public'));

  runCmd = function(cmd) {
    var i, _i, _len, _results;

    _results = [];
    for (_i = 0, _len = vlcInstances.length; _i < _len; _i++) {
      i = vlcInstances[_i];
      _results.push((function(i) {
        return exec("curl " + i.host + ":" + i.port + REQUEST_URL + cmd, function(err) {
          if (err != null) {
            return console.error(err);
          }
        });
      })(i));
    }
    return _results;
  };

  app.get('/player/pause', function(req, res) {
    runCmd('pl_pause');
    return res.end();
  });

  app.get('/player/stop', function(req, res) {
    runCmd('pl_stop');
    return res.end();
  });

  app.get('/player/next', function(req, res) {
    runCmd('pl_next');
    return res.end();
  });

  app.get('/player/prev', function(req, res) {
    runCmd('pl_previous');
    return res.end();
  });

  app.get('/clients/*', function(req, res) {
    res.send(JSON.stringify(vlcInstances));
    return res.end();
  });

  app.listen(3000);

}).call(this);
